const committee = [
  {
    id: '',
    name: 'Jhankar Mahbub',
    age: 32,
    salary: 500000,
    skills:
      'JavaScript, ES6, React, Redux, Angular6, Bootstrap, Data visualization, Material Design',
    quality: 'Sr. Web Developer,Runner,Author,Entrepreneur,Teacher',
    achievement: 'Programming Hero',
    nationality: 'Bangladesh',
  },
  {
    id: '',
    name: 'Mark Elliot Zuckerberg',
    age: 37,
    salary: 179100000,
    skills:
      'C,C++,AI,JavaScript, ES6, React, Redux, Angular6, Bootstrap, Data visualization, Material Design',
    quality:
      'Equanimity,Critical thinking,Problem-solving,Entrepreneur,Effective communication',
    achievement: 'Facebook Inc',
    nationality: 'British',
  },
  {
    id: '',
    name: 'Bjarne Stroustrup',
    age: 70,
    salary: 541212,
    skills: 'Machine Language,High level language,',
    quality: 'Invent C++',
    achievement: 'C++',
    nationality: 'British',
  },
  {
    id: '',
    name: 'Brendan Eich',
    age: 60,
    salary: 1258000,
    skills: 'Machine Language, C, C++, JavaScript,High Level Languages',
    quality: 'Invent JavaScript, Mozilla, NetScape',
    achievement: 'JavaScript',
    nationality: 'British',
  },
  {
    id: '',
    name: 'Elon Reeve Musk',
    age: 50,
    salary: 7000000,
    skills: 'Basic,C,C++',
    quality: 'Tesla, SpaceX,GPT-3,AI,IOT',
    achievement: 'SpaceX',
    nationality: 'British',
  },
  {
    id: '',
    name: 'Tim Berners-Lee',
    age: 66,
    salary: 5500000,
    skills: 'Computer Scientist',
    quality: 'inventor of the World Wide Web',
    achievement: 'www',
    nationality: 'British',
  },
  {
    id: '',
    name: 'Brian Kernighan',
    age: 79,
    salary: 9856231,
    skills: 'Canadian computer scientist',
    quality: ' Unix, AWK, AMPL, Kernighan–Lin algorithm',
    achievement: 'C Programming',
    nationality: 'Canada',
  },
];
